---

- name: Consul
  hosts: ec2 for AWS, gce for Google Cloud
  connection: ssh

  tasks:
  - name: Downloading Consul
    command: wget -P /home/$USER/ https://releases.hashicorp.com/consul/0.8.5/consul_0.8.5_linux_amd64.zip 

  - name: Unzipping
    command: sudo unzip /home/$USER/consul_0.8.5_linux_amd64.zip

  - name: Adding permissions
    command: sudo chmod +x /home/$USER/consul
 
  - name: Changing dir
    command: sudo mv /home/$USER/consul /usr/bin/ 

  - name: Creating Dir and changing dir
    command: mkdir /opt/consul-ui && cd /opt/consul-ui

  - name: Downloading Consul UI
    command: wget https://releases.hashicorp.com/consul/0.7.2/consul_0.7.2_web_ui.zip

  - name: Unzipping Consul UI
    command: unzip consul_0.7.2_web_ui.zip
 
  - name: Running consul UI. Check http://localhost:8500/ui
    command: consul agent -dev -ui -data-dir /tmp/consul

  - name: Runnning Consul
    command: consul agent -dev -data-dir=/tmp/consul -d

       


      
