---

- name: Configure GCE instances
  hosts: gce
  connection: ssh
  sudo: true
  ignore_errors: yes


  tasks:
  - name: Update the machine
    become: yes
    command: apt-get clean && update -y
    
  - name: Installing essentials
    command: apt-get install apt-transport-https ca-certificates curl software-properties-common unzip -y
  
  - name: Installing docker
    command: sudo apt-get install docker.io -y

  - name: Adding docker user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed
    
