---

- name: Nomad
  hosts: gce
  connection: ssh

  tasks:
  - name: Installing Nomad
    command: wget -P /home/$USER/ https://releases.hashicorp.com/nomad/0.5.6/nomad_0.5.6_linux_amd64.zip 

  - name: Unzipping
    command: sudo unzip /home/$USER/nomad_0.5.6_linux_amd64.zip

  - name: Adding permissions
    command: sudo chmod +x /home/$USER/nomad
 
  - name: Adding to BASH
    command: sudo mv /home/$USER/nomad /usr/local/bin/ 

  - name: Creating nomad.d
    command: sudo mkdir -p /etc/nomad.d       

  - name: Changing permissions nomad.d
    command: sudo chmod a+w /etc/nomad.d

  - name: Creating /opt/nomad/data
    command: sudo mkdir -p /opt/nomad/data

  - name: Creating /var/log/nomad/
    command: sudo mkdir -p /var/log/nomad
 
  - name: Changing Permissions
    command: sudo chmod a+w /var/log/nomad

  - name: Copying server.hcl
    copy: src=server.hcl dest=~/home/$USER/

  - name: Running Nomad Agent
    command: sudo nohup nomad agent -config /etc/nomad.d/server.hcl &>nomad.log  &
